baseURL = 'https://nachiketa3299.github.io'
languageCode = 'ko'
copyright = 'rzenburn'
title = 'Even idiots can make game'

theme = 'hugo-theme-nostyleplease'

[markup.goldmark.renderer]
  unsafe = true

[markup]
  [markup.highlight]
    anchorLineNos = true
    lineNos = true
    tabWidth = 2
    codeFences = true
    lineNumbersInTable = false
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 3
    ordered = false

[params]
  [params.theme_config]
    appearance = 'light'
    back_home_text = "<< 뒤로"
    isShowFooter = true
    isListGroupByDate = false

[taxonomies]
  tag = "tags"

[services]
  [services.disqus]
    shortname = 'even-idiots-can-make-games'