baseURL = 'https://nachiketa3299.github.io'
languageCode = 'ko'
copyright = 'rzenburn'
title = 'Even idiots can make game'

theme = 'hugo-theme-nostyleplease'

[markup.goldmark.renderer]
unsafe = true

[markup]
[markup.highlight]
lineNos = true
tabWidth = 2
codeFences = true
lineNumbersInTable = false

[params]
[params.theme_config]
appearance = 'light'
back_home_text = "<<back"
isShowFooter = false
