title: "Even Idiots Can Make Game"
theme: soda-note-theme

menu:
  main:
    - name: "Home"
      url: "/"
      weight: 1
    - name: "PS"
      url: "/ps/"
      weight: 2
    - name: "Categories"
      url: "/categories/"
      weight: 3
    - name: "Tags"
      url: "/tags/"
      weight: 4
    - name: "All Posts"
      url: "/all-posts/"
      weight: 5

locale: ko-kr
timezone: Asia/Seoul

taxonomies:
  category: "categories"
  tag: "tags"

capitalizeListTitles: false

services:
  googleAnalytics:
    id: G-TF4NJ6XV1W

params:
  giscus:
    repo: "nachiketa3299/RUB"
    repoId: "R_kgDOMCjEUg"
    category: "Announcements"
    categoryId: "DIC_kwDOMCjEUs4C8O0b"
    mapping: "pathname"
    strict: "0"
    reactionsEnabled: "1"
    emitMetadata: "0"
    inputPosition: "bottom"
    theme: "light"
    lang: "ko"

markup:
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: true
    lineNumbersInTable: true
    lineAnchors: ''
    lineNos: true
    lineNoStart: 1
    tabWidth: 2
    style: monokai
  tableOfContents:
    startLevel: 1
    endLevel: 3
    ordered: false
  goldmark:
    renderer:
      unsafe: true
    extensions:
      extras:
        mark:
          enable: true