baseURL = 'https://nachiketa3299.github.io/RUB/'
languageCode = 'ko'
copyright = 'rzenburn'
title = 'Even idiots can make game'

theme = 'hugo-theme-nostyleplease'

[markup.goldmark.renderer]
  unsafe = true

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    lineNumbersInTable = true
    lineAnchors = ''
    lineNoStart = 1
    lineNos = true
    noClasses = true
    tabWidth = 2
    style = 'monokai'
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 3
    ordered = false
  [markup.goldmark.extensions.extras.mark]
    enable = true

[params]
  description = "디스크립션 테스트"
  [params.theme_config]
    appearance = 'light'
    back_home_text = "<< 뒤로"
    isShowFooter = true
    isListGroupByDate = false
    show_description = false

[taxonomies]
  tag = "tags"

[services]
  [services.disqus]
    shortname = 'even-idiots-can-make-games'
  [services.googleAnalytics]
    id = 'G-TF4NJ6XV1W'

enableRobotsTxt = true

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

timeZone = "Asia/Seoul"